// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Philadelphus.Infrastructure.Persistence.EF.PostgreSQL.Contexts;

#nullable disable

namespace Philadelphus.Infrastructure.Persistence.EF.PostgreSQL.Migrations.MainEntitiesPhiladelphusContextMigrations
{
    [DbContext(typeof(MainEntitiesPhiladelphusContext))]
    partial class MainEntitiesPhiladelphusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRoot", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.PrimitiveCollection<Guid[]>("DataStoragesUuids")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnDataStorageUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("data_storage_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Uuid")
                        .HasName("tree_roots_pkey");

                    b.ToTable("tree_roots", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRootMembers.TreeLeave", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentTreeNodeUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTreeRootUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentUuid")
                        .HasColumnType("uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Uuid")
                        .HasName("tree_leaves_pkey");

                    b.HasIndex("ParentTreeRootUuid");

                    b.HasIndex("ParentUuid");

                    b.ToTable("tree_leaves", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRootMembers.TreeNode", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentTreeNodeUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_tree_node_uuid");

                    b.Property<Guid?>("ParentTreeRootUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_tree_root_uuid");

                    b.Property<Guid?>("ParentUuid")
                        .HasColumnType("uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("TreeRootUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Uuid")
                        .HasName("tree_nodes_pkey");

                    b.HasIndex("ParentTreeNodeUuid");

                    b.HasIndex("ParentTreeRootUuid");

                    b.HasIndex("TreeRootUuid");

                    b.ToTable("tree_nodes", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Attributes.ElementAttribute", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("ValueTypeUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("value_type_uuid");

                    b.Property<Guid?>("ValueUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("value_uuid");

                    b.HasKey("Uuid")
                        .HasName("element_attributes_pkey");

                    b.ToTable("element_attributes", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRoot", b =>
                {
                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Properties.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeRootUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ContentUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("ContentUpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("content_updated_by");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("session_user")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeRootUuid");

                            b1.ToTable("tree_roots", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("TreeRootUuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRootMembers.TreeLeave", b =>
                {
                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRoot", "ParentTreeRoot")
                        .WithMany()
                        .HasForeignKey("ParentTreeRootUuid");

                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRootMembers.TreeNode", "ParentTreeNode")
                        .WithMany()
                        .HasForeignKey("ParentUuid");

                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Properties.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeLeaveUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ContentUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("ContentUpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("content_updated_by");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("session_user")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeLeaveUuid");

                            b1.ToTable("tree_leaves", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("TreeLeaveUuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ParentTreeNode");

                    b.Navigation("ParentTreeRoot");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRootMembers.TreeNode", b =>
                {
                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRootMembers.TreeNode", "ParentTreeNode")
                        .WithMany()
                        .HasForeignKey("ParentTreeNodeUuid");

                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRoot", "ParentTreeRoot")
                        .WithMany()
                        .HasForeignKey("ParentTreeRootUuid");

                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRoot", null)
                        .WithMany("ChildTreeNodes")
                        .HasForeignKey("TreeRootUuid");

                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Properties.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeNodeUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ContentUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("ContentUpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("content_updated_by");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("session_user")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeNodeUuid");

                            b1.ToTable("tree_nodes", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("TreeNodeUuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ParentTreeNode");

                    b.Navigation("ParentTreeRoot");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Attributes.ElementAttribute", b =>
                {
                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Properties.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("ElementAttributeUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ContentUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("ContentUpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("content_updated_by");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("ElementAttributeUuid");

                            b1.ToTable("element_attributes", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("ElementAttributeUuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.TreeRoot", b =>
                {
                    b.Navigation("ChildTreeNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
