// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Philadelphus.Infrastructure.Persistence.EF.SQLite.Contexts;

#nullable disable

namespace Philadelphus.Infrastructure.Persistence.EF.SQLite.Migrations.ShrubMembersContextMigrations
{
    [DbContext(typeof(SqliteEfShrubMembersContext))]
    partial class SqliteEfShrubMembersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTree", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnDataStorageUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_storage_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.HasKey("Uuid")
                        .HasName("working_trees_pkey");

                    b.ToTable("working_trees", "shrub_members");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeLeave", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OwningWorkingTreeUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("owning_working_tree_uuid");

                    b.Property<Guid?>("ParentTreeNodeUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_tree_node_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<int>("SystemBaseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("data_type_id");

                    b.HasKey("Uuid")
                        .HasName("tree_leaves_pkey");

                    b.HasIndex("OwningWorkingTreeUuid");

                    b.HasIndex("ParentTreeNodeUuid");

                    b.ToTable("tree_leaves", "shrub_members");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeNode", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OwningWorkingTreeUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("owning_working_tree_uuid");

                    b.Property<Guid?>("ParentTreeNodeUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_tree_node_uuid");

                    b.Property<Guid?>("ParentTreeRootUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_tree_root_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<int>("SystemBaseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("data_type_id");

                    b.HasKey("Uuid")
                        .HasName("tree_nodes_pkey");

                    b.HasIndex("OwningWorkingTreeUuid");

                    b.HasIndex("ParentTreeNodeUuid");

                    b.HasIndex("ParentTreeRootUuid");

                    b.ToTable("tree_nodes", "shrub_members");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeRoot", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OwningWorkingTreeUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("owning_working_tree_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.HasKey("Uuid")
                        .HasName("tree_roots_pkey");

                    b.HasIndex("OwningWorkingTreeUuid")
                        .IsUnique();

                    b.ToTable("tree_roots", "shrub_members");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Attributes.ElementAttribute", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_code");

                    b.Property<Guid>("DeclaringOwnerUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("declaring_owner_uuid");

                    b.Property<Guid>("DeclaringUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("declaring_uuid");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsCollectionValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_collection_value");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("OverrideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("override_id");

                    b.Property<Guid>("OwnerUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_uuid");

                    b.Property<Guid>("OwningWorkingTreeUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("owning_working_tree_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("ValueTypeUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("value_type_uuid");

                    b.Property<Guid?>("ValueUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("value_uuid");

                    b.PrimitiveCollection<string>("ValuesUuids")
                        .HasColumnType("TEXT")
                        .HasColumnName("values_uuids");

                    b.Property<int>("VisibilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("visibility_id");

                    b.HasKey("Uuid")
                        .HasName("element_attributes_pkey");

                    b.HasIndex("OwningWorkingTreeUuid");

                    b.ToTable("element_attributes", "shrub_members_content");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTree", b =>
                {
                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Properties.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("WorkingTreeUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_by");

                            b1.HasKey("WorkingTreeUuid");

                            b1.ToTable("working_trees", "shrub_members");

                            b1.WithOwner()
                                .HasForeignKey("WorkingTreeUuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeLeave", b =>
                {
                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTree", null)
                        .WithMany("ContentLeaves")
                        .HasForeignKey("OwningWorkingTreeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeNode", null)
                        .WithMany("ChildLeaves")
                        .HasForeignKey("ParentTreeNodeUuid");

                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Properties.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeLeaveUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeLeaveUuid");

                            b1.ToTable("tree_leaves", "shrub_members");

                            b1.WithOwner()
                                .HasForeignKey("TreeLeaveUuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeNode", b =>
                {
                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTree", null)
                        .WithMany("ContentNodes")
                        .HasForeignKey("OwningWorkingTreeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeNode", null)
                        .WithMany("ChildNodes")
                        .HasForeignKey("ParentTreeNodeUuid");

                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeRoot", null)
                        .WithMany("ChildNodes")
                        .HasForeignKey("ParentTreeRootUuid");

                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Properties.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeNodeUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeNodeUuid");

                            b1.ToTable("tree_nodes", "shrub_members");

                            b1.WithOwner()
                                .HasForeignKey("TreeNodeUuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeRoot", b =>
                {
                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTree", null)
                        .WithOne("ContentRoot")
                        .HasForeignKey("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeRoot", "OwningWorkingTreeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Properties.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeRootUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeRootUuid");

                            b1.ToTable("tree_roots", "shrub_members");

                            b1.WithOwner()
                                .HasForeignKey("TreeRootUuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Attributes.ElementAttribute", b =>
                {
                    b.HasOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTree", null)
                        .WithMany("ContentAttributes")
                        .HasForeignKey("OwningWorkingTreeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.Entities.MainEntityContent.Properties.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("ElementAttributeUuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("TEXT")
                                .HasColumnName("updated_by");

                            b1.HasKey("ElementAttributeUuid");

                            b1.ToTable("element_attributes", "shrub_members_content");

                            b1.WithOwner()
                                .HasForeignKey("ElementAttributeUuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTree", b =>
                {
                    b.Navigation("ContentAttributes");

                    b.Navigation("ContentLeaves");

                    b.Navigation("ContentNodes");

                    b.Navigation("ContentRoot")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeNode", b =>
                {
                    b.Navigation("ChildLeaves");

                    b.Navigation("ChildNodes");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.Entities.MainEntities.PhiladelphusRepositoryMembers.ShrubMembers.WorkingTreeMembers.TreeRoot", b =>
                {
                    b.Navigation("ChildNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
