// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Philadelphus.PostgreEfRepository.Contexts;

#nullable disable

namespace Philadelphus.PostgreEfRepository.Migrations.TreeRepositoriesPhiladelphusContextMigrations
{
    [DbContext(typeof(TreeRepositoriesPhiladelphusContext))]
    [Migration("20251005203810_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRepository", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.PrimitiveCollection<Guid[]>("ChildTreeRootsGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("child_tree_roots_uuids");

                    b.PrimitiveCollection<Guid[]>("DataStoragesGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("data_storages_uuids");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnDataStorageGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("data_storage_uuid");

                    b.HasKey("Guid")
                        .HasName("tree_repositories_pkey");

                    b.ToTable("tree_repositories", "repositories");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRepository", b =>
                {
                    b.OwnsOne("Philadelphus.InfrastructureEntities.MainEntities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeRepositoryGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<string>("CreatedOn")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("created_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by");

                            b1.Property<string>("DeletedOn")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("deleted_at");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("updated_by");

                            b1.Property<string>("UpdatedContentBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_updated_by");

                            b1.Property<string>("UpdatedContentOn")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("UpdatedOn")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("updated_at");

                            b1.HasKey("TreeRepositoryGuid");

                            b1.ToTable("tree_repositories", "repositories");

                            b1.WithOwner()
                                .HasForeignKey("TreeRepositoryGuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
