// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Philadelphus.PostgreEfRepository.Contexts;

#nullable disable

namespace Philadelphus.PostgreEfRepository.Migrations.TreeRepositoriesPhiladelphusContextMigrations
{
    [DbContext(typeof(TreeRepositoriesPhiladelphusContext))]
    partial class TreeRepositoriesPhiladelphusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.AuditInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_on");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DeletedOn")
                        .HasColumnType("text")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("RepositoryElementUuid")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedContentBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_content_by");

                    b.Property<string>("UpdatedContentOn")
                        .HasColumnType("text")
                        .HasColumnName("updated_content_on");

                    b.Property<string>("UpdatedOn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("audit_infos_pkey");

                    b.ToTable("audit_infos", "general");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<int>("AuditInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("HasContent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentGuid")
                        .HasColumnType("text");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("main_entity_base_pkey");

                    b.HasIndex("AuditInfoId");

                    b.ToTable("main_entity", "general");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRepository", b =>
                {
                    b.HasBaseType("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase");

                    b.PrimitiveCollection<List<Guid>>("ChildTreeRootGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("OwnDataStorageGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("own_data_storage_guid");

                    b.ToTable("tree_repositories", "repositories");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase", b =>
                {
                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.AuditInfo", "AuditInfo")
                        .WithMany()
                        .HasForeignKey("AuditInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditInfo");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRepository", b =>
                {
                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase", null)
                        .WithOne()
                        .HasForeignKey("Philadelphus.InfrastructureEntities.MainEntities.TreeRepository", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
