// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Philadelphus.PostgreEfRepository.Contexts;

#nullable disable

namespace Philadelphus.PostgreEfRepository.Migrations.MainEntitiesPhiladelphusContextMigrations
{
    [DbContext(typeof(MainEntitiesPhiladelphusContext))]
    [Migration("20251109123225_AddAttributes2")]
    partial class AddAttributes2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.ElementAttribute", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<Guid>("ValueTypeUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("value_type_uuid");

                    b.Property<Guid>("ValueUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("value_uuid");

                    b.HasKey("Guid")
                        .HasName("element_attributes_pkey");

                    b.ToTable("element_attributes", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.TreeLeave", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTreeNodeGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTreeRootGuid")
                        .HasColumnType("uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Guid")
                        .HasName("tree_leaves_pkey");

                    b.HasIndex("ParentGuid");

                    b.HasIndex("ParentTreeRootGuid");

                    b.ToTable("tree_leaves", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.TreeNode", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTreeNodeGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_tree_node_uuid");

                    b.Property<Guid?>("ParentTreeRootGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_tree_root_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("TreeRootGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid")
                        .HasName("tree_nodes_pkey");

                    b.HasIndex("ParentTreeNodeGuid");

                    b.HasIndex("ParentTreeRootGuid");

                    b.HasIndex("TreeRootGuid");

                    b.ToTable("tree_nodes", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.TreeRoot", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.PrimitiveCollection<Guid[]>("DataStoragesGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnDataStorageGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("data_storage_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Guid")
                        .HasName("tree_roots_pkey");

                    b.ToTable("tree_roots", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.ElementAttribute", b =>
                {
                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.MainEntities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("ElementAttributeGuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ContentUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("ContentUpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("content_updated_by");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("ElementAttributeGuid");

                            b1.ToTable("element_attributes", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("ElementAttributeGuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.TreeLeave", b =>
                {
                    b.HasOne("Philadelphus.Infrastructure.Persistence.MainEntities.TreeNode", "ParentTreeNode")
                        .WithMany()
                        .HasForeignKey("ParentGuid");

                    b.HasOne("Philadelphus.Infrastructure.Persistence.MainEntities.TreeRoot", "ParentTreeRoot")
                        .WithMany()
                        .HasForeignKey("ParentTreeRootGuid");

                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.MainEntities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeLeaveGuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ContentUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("ContentUpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("content_updated_by");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("session_user")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeLeaveGuid");

                            b1.ToTable("tree_leaves", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("TreeLeaveGuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ParentTreeNode");

                    b.Navigation("ParentTreeRoot");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.TreeNode", b =>
                {
                    b.HasOne("Philadelphus.Infrastructure.Persistence.MainEntities.TreeNode", "ParentTreeNode")
                        .WithMany()
                        .HasForeignKey("ParentTreeNodeGuid");

                    b.HasOne("Philadelphus.Infrastructure.Persistence.MainEntities.TreeRoot", "ParentTreeRoot")
                        .WithMany()
                        .HasForeignKey("ParentTreeRootGuid");

                    b.HasOne("Philadelphus.Infrastructure.Persistence.MainEntities.TreeRoot", null)
                        .WithMany("ChildTreeNodes")
                        .HasForeignKey("TreeRootGuid");

                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.MainEntities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeNodeGuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ContentUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("ContentUpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("content_updated_by");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("session_user")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeNodeGuid");

                            b1.ToTable("tree_nodes", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("TreeNodeGuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ParentTreeNode");

                    b.Navigation("ParentTreeRoot");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.TreeRoot", b =>
                {
                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.MainEntities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeRootGuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ContentUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("ContentUpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("content_updated_by");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("session_user")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeRootGuid");

                            b1.ToTable("tree_roots", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("TreeRootGuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.TreeRoot", b =>
                {
                    b.Navigation("ChildTreeNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
