// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Philadelphus.PostgreEfRepository.Contexts;

#nullable disable

namespace Philadelphus.PostgreEfRepository.Migrations.MainEntitiesPhiladelphusContextMigrations
{
    [DbContext(typeof(MainEntitiesPhiladelphusContext))]
    [Migration("20251005203816_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeLeave", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentGuid")
                        .HasColumnType("uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Guid")
                        .HasName("tree_leaves_pkey");

                    b.HasIndex("ParentGuid");

                    b.ToTable("tree_leaves", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeNode", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentGuid")
                        .HasColumnType("uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("TreeRootGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid")
                        .HasName("tree_nodes_pkey");

                    b.HasIndex("ParentGuid");

                    b.HasIndex("TreeRootGuid");

                    b.ToTable("tree_nodes", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRoot", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text")
                        .HasColumnName("custom_code");

                    b.PrimitiveCollection<Guid[]>("DataStoragesGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnDataStorageGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("data_storage_uuid");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Guid")
                        .HasName("tree_roots_pkey");

                    b.ToTable("tree_roots", "main_entities");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeLeave", b =>
                {
                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.TreeNode", "ParentTreeNode")
                        .WithMany()
                        .HasForeignKey("ParentGuid");

                    b.OwnsOne("Philadelphus.InfrastructureEntities.MainEntities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeLeaveGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<string>("CreatedOn")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("created_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by");

                            b1.Property<string>("DeletedOn")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("deleted_at");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("updated_by");

                            b1.Property<string>("UpdatedContentBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_updated_by");

                            b1.Property<string>("UpdatedContentOn")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("UpdatedOn")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("updated_at");

                            b1.HasKey("TreeLeaveGuid");

                            b1.ToTable("tree_leaves", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("TreeLeaveGuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ParentTreeNode");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeNode", b =>
                {
                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.TreeNode", "ParentTreeNode")
                        .WithMany()
                        .HasForeignKey("ParentGuid");

                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.TreeRoot", "ParentTreeRoot")
                        .WithMany()
                        .HasForeignKey("ParentGuid");

                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.TreeRoot", null)
                        .WithMany("ChildTreeNodes")
                        .HasForeignKey("TreeRootGuid");

                    b.OwnsOne("Philadelphus.InfrastructureEntities.MainEntities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeNodeGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<string>("CreatedOn")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("created_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by");

                            b1.Property<string>("DeletedOn")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("deleted_at");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("updated_by");

                            b1.Property<string>("UpdatedContentBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_updated_by");

                            b1.Property<string>("UpdatedContentOn")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("UpdatedOn")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("updated_at");

                            b1.HasKey("TreeNodeGuid");

                            b1.ToTable("tree_nodes", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("TreeNodeGuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ParentTreeNode");

                    b.Navigation("ParentTreeRoot");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRoot", b =>
                {
                    b.OwnsOne("Philadelphus.InfrastructureEntities.MainEntities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeRootGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("created_by");

                            b1.Property<string>("CreatedOn")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("created_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deleted_by");

                            b1.Property<string>("DeletedOn")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("deleted_at");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("updated_by");

                            b1.Property<string>("UpdatedContentBy")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_updated_by");

                            b1.Property<string>("UpdatedContentOn")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("UpdatedOn")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("updated_at");

                            b1.HasKey("TreeRootGuid");

                            b1.ToTable("tree_roots", "main_entities");

                            b1.WithOwner()
                                .HasForeignKey("TreeRootGuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRoot", b =>
                {
                    b.Navigation("ChildTreeNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
