// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Philadelphus.PostgreEfRepository.Contexts;

#nullable disable

namespace Philadelphus.PostgreEfRepository.Migrations.MainEntitiesPhiladelphusContextMigrations
{
    [DbContext(typeof(MainEntitiesPhiladelphusContext))]
    [Migration("20250921093641_SomeChanges210925")]
    partial class SomeChanges210925
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.AuditInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletedOn")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RepositoryElementUuid")
                        .HasColumnType("integer")
                        .HasColumnName("repository_element_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedContentBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedContentOn")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("audit_info_pkey");

                    b.ToTable("audit_info", (string)null);
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("repository_element_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<int>("AuditInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<bool>("HasContent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentGuid")
                        .HasColumnType("text");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuditInfoId");

                    b.ToTable("repository_elements", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.ElementAttribute", b =>
                {
                    b.HasBaseType("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase");

                    b.PrimitiveCollection<List<long>>("ValueIds")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeElementAttributeValue", b =>
                {
                    b.HasBaseType("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase");

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeLeave", b =>
                {
                    b.HasBaseType("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase");

                    b.PrimitiveCollection<List<long>>("AttributeGuids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<long>("ParentTreeNodeGuid")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("leave_details", (string)null);
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeNode", b =>
                {
                    b.HasBaseType("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase");

                    b.PrimitiveCollection<List<long>>("AttributeGuids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.PrimitiveCollection<List<long>>("ChildTreeLeaveGuids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.PrimitiveCollection<List<long>>("ChildTreeNodeGuids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<long>("ParentTreeNodeGuid")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentTreeRootGuid")
                        .HasColumnType("bigint");

                    b.ToTable("node_details", (string)null);
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRepository", b =>
                {
                    b.HasBaseType("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase");

                    b.PrimitiveCollection<List<Guid>>("ChildTreeRootGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("OwnDataStorageGuid")
                        .HasColumnType("uuid");

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRoot", b =>
                {
                    b.HasBaseType("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase");

                    b.PrimitiveCollection<List<long>>("AttributeGuids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.PrimitiveCollection<List<long>>("ChildTreeNodeGuids")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<Guid>("OwnDataStorageGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentTreeRepositoryGuid")
                        .HasColumnType("uuid");

                    b.ToTable("root_details", (string)null);
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase", b =>
                {
                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.AuditInfo", "AuditInfo")
                        .WithMany()
                        .HasForeignKey("AuditInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditInfo");
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeLeave", b =>
                {
                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase", null)
                        .WithOne()
                        .HasForeignKey("Philadelphus.InfrastructureEntities.MainEntities.TreeLeave", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeNode", b =>
                {
                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase", null)
                        .WithOne()
                        .HasForeignKey("Philadelphus.InfrastructureEntities.MainEntities.TreeNode", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRepository", b =>
                {
                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase", null)
                        .WithOne()
                        .HasForeignKey("Philadelphus.InfrastructureEntities.MainEntities.TreeRepository", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Philadelphus.InfrastructureEntities.MainEntities.TreeRoot", b =>
                {
                    b.HasOne("Philadelphus.InfrastructureEntities.MainEntities.MainEntityBase", null)
                        .WithOne()
                        .HasForeignKey("Philadelphus.InfrastructureEntities.MainEntities.TreeRoot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
