// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Philadelphus.Infrastructure.Persistence.EF.PostgreSQL.Contexts;

#nullable disable

namespace Philadelphus.Infrastructure.Persistence.EF.PostgreSQL.Migrations.TreeRepositoriesPhiladelphusContextMigrations
{
    [DbContext(typeof(TreeRepositoriesPhiladelphusContext))]
    [Migration("20251109114616_AddAttributes")]
    partial class AddAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.TreeRepository", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<Guid[]>("ChildTreeRootsGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("child_tree_roots_uuids");

                    b.PrimitiveCollection<Guid[]>("DataStoragesGuids")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("data_storages_uuids");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnDataStorageGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("data_storage_uuid");

                    b.HasKey("Guid")
                        .HasName("tree_repositories_pkey");

                    b.ToTable("tree_repositories", "repositories");
                });

            modelBuilder.Entity("Philadelphus.Infrastructure.Persistence.MainEntities.TreeRepository", b =>
                {
                    b.OwnsOne("Philadelphus.Infrastructure.Persistence.MainEntities.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("TreeRepositoryGuid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ContentUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("content_updated_at");

                            b1.Property<string>("ContentUpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("content_updated_by");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("session_user")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("text")
                                .HasColumnName("deleted_by");

                            b1.Property<bool>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("TreeRepositoryGuid");

                            b1.ToTable("tree_repositories", "repositories");

                            b1.WithOwner()
                                .HasForeignKey("TreeRepositoryGuid");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
